@Library('jte-example') _

pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
       checkout scm
      }
    }

    stage('Hello') {
      steps {
        hello()
      }
    }

    stage('Clean') {
      steps {
        cleanProject()
      }
    }

  }
}