@Library('jte-example') _

pipeline {
    environment {
        //choosen semantic version
        IS_CRON_JOB = "${currentBuild.rawBuild.getCause(hudson.triggers.TimerTrigger.TimerTriggerCause) != null ? 'true' : 'false'}"
    }
  agent any

  triggers {
    cron('0 10 * * *')
  }
  stages {
    stage('Checkout') {
      steps {
       checkout scm
      }
    }

    stage('Hello') {
      steps {
        helloProject('Alper')
      }
    }

    stage('Clean') {
      steps {
        cleanProject()
      }
    }

    stage('Build') {
      steps {
        buildProject()
      }
    }

    stage('Trigger-Project') {
      steps {
        triggerProject()
      }
    }

  }
}